version: "3"
services:
  ocular-models-server:
    container_name: ocular-models-server
    build:
      context: .
      dockerfile: packages/ocular-models-server/Dockerfile.models
    ports:
      - 8000:8000
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - ./log4j.properties:/opt/bitnami/zookeeper/conf/log4j.properties

  kafka:
    image: confluentinc/cp-kafka:latest
    user: root
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092,EXTERNAL://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://kafka:29092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG4J_LOGGERS=org.apache.zookeeper=ERROR,org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR
    volumes:
      - ./Kafka:/bitnami/kafka
      - ./log4j.properties:/etc/kafka/log4j.properties

  ocular-db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ocular
      POSTGRES_USER: ocular
      POSTGRES_DB: ocular

  ocular-backend:
    container_name: ocular-backend
    build:
      context: .
      dockerfile: packages/ocular/Dockerfile.local
    depends_on:
      ocular-db:
        condition: service_started
      qdrant:
        condition: service_started
      ocular-models-server:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - 9000:9000
    command: /bin/sh -c "npm run typeorm:local migration:run && npm run local"
    environment:
      - DATABASE_URL=postgresql://ocular:ocular@ocular-db:5432/ocular
      - DATABASE_NAME=ocular
      - NODE_ENV=development
      - QDRANT_DB_URL=http://qdrant:6333
      - UI_CORS=http://ocular-ui:9000
      - REDIS_URL=redis:6379
      - KAFKA_URL=kafka:29092
      - OCULAR_MODELS_SERVER_URL=http://ocular-models-server:8000

  ocular-ui:
    container_name: ocular-ui
    build:
      context: .
      dockerfile: packages/ocular-ui/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - ocular-backend
