name: Bug report
description: Create a report to help us improve
title: "bug: "
labels: [triage needed, bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in the Ocular project.
  - type: markdown
    attributes:
      value: |
        Before filing a new issue, **please do a quick search** to check that it hasn't already been filed on the issue tracker. You can do this by going to [this link](https://github.com/OcularEngineering/ocular/issues) and typing some words related to the issue in the search box next to the "New issue" button.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A concise description of what issue you're experiencing. **Example:** "When I click on the 'Sign in' button, I expect to be redirected to the login page, but instead I get a 404 error."
    validations:
      required: true
  - type: input
    attributes:
      label: URL of the page where the issue is observed.
      description: The URL of the specific page where you are experiencing the issue (or N/A if not applicable).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the behavior. **Example:** "1. Go to the library page. 2. Click on the 'Sign in' button. 3. See error."

        **Notes:**
          - Please list the full step-by-step instructions. Do not require the reader to infer the steps from watching a video.
          - (For devs) If any feature flags need to be turned on to reproduce the issue, specify them here as well.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen. **Example:** "I expect to be redirected to the login page."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: |
        If applicable, add screenshots or videos to help explain your problem.

        **Tip:** You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Operating System
      description: Please select the operating system you're using. **Example:** "Windows". If you're using multiple Operating systems, please select all that apply.
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
