blank_issues_enabled: true
contact_links:
  - name: Ocular Slack Support
    url: https://join.slack.com/t/ocular-ai/shared_invite/zt-2g7ka0j1c-Tx~Q46MjplNma2Sk2Ruplw
    about: Please ask and answer questions here.
