name: Build Ocular Web UI Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Branch
      uses: actions/checkout@v4

    - name: Set Up Docker Builders
      uses: docker/setup-buildx-action@v3

    - name: Build Ocular UI Image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./packages/ocular-ui/Dockerfile
        push: false
        tags: ocular-ui:latest
