name: Build Ocular Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Branch
      uses: actions/checkout@v4
      
    - name: Set Up Docker Builders
      uses: docker/setup-buildx-action@v3
  
    - name: Build Ocular Backend Image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./packages/ocular/Dockerfile.local
        push: false
        tags: ocularengineering/ocular-backend:build
