name: Build and Push Ocular Models Server on Release and Tag

on:
  push:
    tags:        
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Models Code
      uses: actions/checkout@v2

    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Ocular Model Server Image Docker Build and Push
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./packages/ocular-models-server/Dockerfile.models
        push: true
        tags:
          ocularengineering/ocular-model-server:latest
